name: CI

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: '16'

      - name: Run `npm install`
        run: npm install

      - name: Run `npm run all`
        run: npm run all

      - name: Save PR number
        if: github.actor != 'dependabot[bot]'
        run: echo ${{ github.event.number }} > PR_NUMBER

      - name: Upload artifact with `PR_NUMBER`
        if: github.actor != 'dependabot[bot]'
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: PR_NUMBER
          path: PR_NUMBER

      - name: Upload artifact with `dist` folder
        if: github.actor != 'dependabot[bot]'
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: dist
          path: dist/

      - name: Upload artifact with `covertura.xml`
        if: github.actor != 'dependabot[bot]'
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: cobertura
          path: coverage/cobertura-coverage.xml

      - name: Auto-merge Dependabot PRs
        if: github.actor == 'dependabot[bot]'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge ${{ github.event.number }} --delete-branch --squash -R ${{ github.repository }}
