# Releases a new minor version every time a PR is merged into `master`.
#
# It also generates the `dist` folder inside the tag's commit, keeping
#   the `master` branch clean.
#
# It will also update the major tag v2 to track the latest tag.

name: Release new version

on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          fetch-depth: 0
          ref: master

      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3.5.1
        with:
          node-version: "16"

      - name: Run `npm install`
        run: npm install

      - name: Run `npm run build`
        run: npm run build

      - name: Release new version
        uses: int128/release-typescript-action@8fe76ff937d9a322c48a9ccc2e33fb5731ea80d0 # v1.18.0
        with:
          major-version: 2
